[package]
name = "neo4j_nif"
version = "0.1.0"
authors = ["Christopher Warner <cdw.lighting@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
rustler = "0.37.0"
neo4rs = "0.8.0"
tokio = { version = "1", features = ["full"] }
